project:
  type: website
  output-dir: ./docs

website:
  title: "Home"
  navbar:
    search: true
        
  page-footer: 
    left: "Copyright 2026" 

format:
  html:
    theme:
      - journal
      - custom.scss
    #css: styles.css
    toc: true

editor: visual

